repos:
  - repo: https://github.com/psf/black
    rev: 24.1.0
    hooks:
      - id: black
        args: ["--line-length", "88"]


  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]

  - repo: https://github.com/pre-commit/mirrors-flake8
    rev: 6.1.0
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/pre-commit-hooks
    revs: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
          