name: CI

# Give the workflow permission to write packages so the GITHUB_TOKEN can push images
permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Dev Docker image
        run: docker build -f docker/Dockerfile.dev -t weather-cli-dev .

      - name: Run tests inside Docker
        run: docker run --rm weather-cli-dev

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: pytest.xml
          if-no-files-found: ignore

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
          if-no-files-found: ignore

  build-prod-image:
    runs-on: ubuntu-latest
    needs: lint-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-platform, optional)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push production image to GHCR
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.prod
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/weather-cli:latest

      - name: Confirm image pushed
        run: echo "Pushed image to ghcr.io/${{ github.repository_owner }}/weather-cli:latest"
