name: Security

on:
  schedule:
    - cron: "0 6 * * *" # run daily at 6am UTC
  workflow_dispatch:


jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          pip install --upgrade pip safety
          safety check --full-report
